version: '2'
services:

  app:
    build: ./app
    volumes:
      - './app:/usr/src/app'
    ports:
      - '8888'
    command: ['npm', 'start']

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=_
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - app:app
